name: Deploy Node.js App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Build your static files (REPLACE THIS COMMAND)
      - name: Build
        run: npm start

      # Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
